# Generated by Django 2.1.3 on 2019-01-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='order_date',
            field=models.CharField(default='2019-01-19', max_length=15),
        ),
    ]
