# Generated by Django 2.1.3 on 2019-02-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0003_auto_20190121_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='order_date',
            field=models.CharField(default='2019-02-05', max_length=15),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
