# Generated by Django 2.1.3 on 2019-02-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190207_2010'),
        ('usercart', '0004_auto_20190205_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='payment',
        ),
        migrations.AddField(
            model_name='myorder',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.OrderItem'),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='order_date',
            field=models.CharField(default='2019-02-07', max_length=15),
        ),
    ]
