# Generated by Django 2.1.4 on 2018-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181230_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Please give rating out of 5', null=True),
        ),
    ]
