# Generated by Django 2.1.4 on 2018-12-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181230_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('sub_category', models.CharField(max_length=150, verbose_name='Sub Category')),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=1, null=True, verbose_name='Gender')),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('sub_category', models.CharField(max_length=150, verbose_name='Sub Category')),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=1, null=True, verbose_name='Gender')),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('size', models.CharField(blank=True, max_length=150, null=True)),
                ('os', models.CharField(blank=True, max_length=150, null=True)),
                ('ram', models.CharField(blank=True, choices=[('', '--Select--'), ('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB')], default='', max_length=50, null=True)),
                ('storage', models.CharField(blank=True, choices=[('', '--Select--'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('500', '500 GB'), ('1', '1 TB'), ('2', '2 GB')], default='', max_length=50, null=True)),
                ('camera', models.CharField(blank=True, choices=[('', '--Select--'), ('1.2', '1.2 MP'), ('2', '2 MP'), ('5', '5 MP'), ('8', '8 MP'), ('12', '12 MP'), ('16', '16 MP'), ('20', '20 MP'), ('28', '28 MP')], default='', max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
