# Generated by Django 2.1.4 on 2018-12-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_accessories_electronics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='size',
        ),
        migrations.AddField(
            model_name='electronics',
            name='screen_size',
            field=models.CharField(blank=True, help_text='Please enter screen size like - 15.6,5.5 etc', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(blank=True, help_text='Please enter brand like - Red,brown etc', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.CharField(blank=True, help_text='Please enter size like - M,S,L etc', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='color',
            field=models.CharField(blank=True, help_text='Please enter brand like - Red,brown etc', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='size',
            field=models.CharField(blank=True, help_text='Please enter size like - M,S,L etc', max_length=150, null=True),
        ),
    ]
