# Generated by Django 2.1.4 on 2019-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_myorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='review_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='order_date',
            field=models.CharField(default='2019-01-13', max_length=15),
        ),
    ]
