# Generated by Django 2.1.4 on 2019-01-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190113_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mycart',
        ),
        migrations.DeleteModel(
            name='MyOrder',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
