# Generated by Django 2.1.4 on 2019-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190113_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
