# Generated by Django 2.1.3 on 2019-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190113_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='date',
            field=models.CharField(default='2019-01-16', max_length=15),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
