# Generated by Django 2.1.3 on 2019-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190117_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='review_image2',
            field=models.ImageField(blank=True, default='http://dummyimage.com/60x60/666/ffffff&text=No+Image', null=True, upload_to='', verbose_name='Attach image'),
        ),
    ]
