# Generated by Django 2.1.3 on 2019-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190117_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='review_image2',
            field=models.ImageField(default='NoImage.png', upload_to='', verbose_name='Attach image'),
        ),
    ]
