# Generated by Django 2.1.3 on 2019-01-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190117_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
