# Generated by Django 2.1.3 on 2019-01-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190119_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='screen_size',
        ),
        migrations.AddField(
            model_name='accessories',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
