# Generated by Django 2.1.4 on 2019-02-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190119_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='gender',
        ),
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(blank=True, help_text='Please enter brand like - Red,brown etc', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='date',
            field=models.CharField(default='2019-02-02', max_length=15),
        ),
    ]
