# Generated by Django 2.1.4 on 2019-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20190205_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='date',
            field=models.CharField(default='2019-02-09', max_length=15),
        ),
    ]
