# Generated by Django 2.1.3 on 2019-02-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_ids',
            new_name='product_ids_details',
        ),
    ]
