# Generated by Django 2.1.3 on 2019-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0005_auto_20190207_2045'),
        ('payment', '0003_auto_20190207_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='transaction_type',
            field=models.CharField(default='cod', max_length=150),
        ),
    ]
