# Generated by Django 2.1.4 on 2019-02-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190209_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
