# Generated by Django 2.1.4 on 2019-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='deliver_date',
            field=models.CharField(default='2019-02-17', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.CharField(default='2019-02-10', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='Order Placed', max_length=15),
        ),
    ]
