# Generated by Django 2.1.4 on 2018-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181229_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
