# Generated by Django 2.1.4 on 2018-12-30 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181230_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('street_address', models.TextField(verbose_name='Street Address')),
                ('state_choice', models.CharField(choices=[('', '--Select--'), ('MAH', 'Mahashtra'), ('RAJ', 'Rajsthan'), ('GUJ', 'Gujrat'), ('KAN', 'Karnataka')], default='', max_length=5, verbose_name='State')),
                ('pincode', models.IntegerField(verbose_name='Pin-Code')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('', '--Select--'), ('Card', 'DEBIT CARD'), ('Paytm', 'PAYTM'), ('Upi', 'UPI')], default='', max_length=10, verbose_name='Payement Mode')),
                ('cardno', models.IntegerField(verbose_name='Card No')),
                ('paytmno', models.IntegerField(verbose_name='Paytm No')),
                ('upi', models.CharField(max_length=50, verbose_name='UPI')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(help_text='Enter in "YYYY-MM-DD" format', null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(help_text='Exclude +91 Extension', null=True, unique=True, verbose_name='Mobile No'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
