# Generated by Django 2.1.4 on 2018-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181230_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardno',
            field=models.IntegerField(null=True, verbose_name='Card No'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paytmno',
            field=models.IntegerField(null=True, verbose_name='Paytm No'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi',
            field=models.CharField(max_length=50, null=True, verbose_name='UPI'),
        ),
    ]
