# Generated by Django 2.1.4 on 2018-12-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181230_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('', '--Select--'), ('CARD', 'DEBIT CARD'), ('PAYTM', 'PAYTM'), ('UPI', 'UPI')], default='', max_length=10, verbose_name='Payement Mode'),
        ),
    ]
