# Generated by Django 2.1.4 on 2019-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181230_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(help_text='Exclude +91 Extension', null=True, unique=True, verbose_name='Mobile'),
        ),
    ]
